In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import ephem

from sgp4.io import twoline2rv, verify_checksum, fix_checksum
from datetime import datetime
%matplotlib qt5

In [5]:
name = "Tiangong"
line1 = "1 37820U 11053A   15023.16485450  .00033832  00000-0  30285-3 0  7778"
line2 = "2 37820  42.7691  66.2951 0013320 217.5516 243.5266 15.67581469190589"

# year, month, day = calc_epoch(line1.strip().split()[3])
tle_rec = ephem.readtle(name, line1, line2)
print(tle_rec._epoch)
tle_rec.compute('{}'.format(tle_rec._epoch))
# tle_rec.compute('{}/{}/{}'.format(year, int(month), int(day)))

2015/1/23 03:57:23


In [4]:
print(tle_rec.sublong)
print(tle_rec.sublat)
print((tle_rec.elevation)/1000.0)

-10:29:40.8
41:47:42.5
372.64953125


In [50]:
mir = pd.read_csv('satTLEs/mir.txt', header = None)
mir

0
0      1 16609U 86017A   86050.94902635 -.00007594  5...
1      2 16609  51.5707 120.8567 0099192  90.2986 271...
2      1 16609U 86017A   86050.94902635 -.00007594  5...
3      2 16609  51.5707 120.8567 0099192  90.2986 271...
4      1 16609U 86017A   86050.94902635 -.00007594  5...
...                                                  ...
44661  2 16609  51.6427 250.2825 0041887 201.6706 158...
44662  1 16609U 86017A   01082.17420660  .44402778  1...
44663  2 16609  51.6196 249.7886 0026531 205.9392 324...
44664  1 16609U 86017A   01082.20636684  .00382588  1...
44665  2 16609  51.6362 249.6171 0048914 224.8684 134...

[44666 rows x 1 columns]

In [59]:
'''
def replace(x):
    x.replace("16609U 86017A", "16609U")
"16609U       ", "16609U 86017A"
mir = mir.apply(lambda x: x.replace("1 16609U", "16609U"))
'''
for index_label, row_series in mir.iterrows():
    mir.at[index_label, 0] = row_series[0].replace("86017A    ", "86017A   ")

In [60]:
mir.to_csv('mir.txt', index = False, header = None)

In [56]:
mir[19304:19305]

0
19304  1 16609U 86017A    93150.61631262 -.00008903  ...

In [53]:
df = pd.read_csv('sat44597.csv', header = None)
df

0       1        2            3            4         5         6  \
0    1  44597U   12039H  19275.57269     0.000287   00000-0   38050-3   
1    2   44597  97.6159    284.63930  3322.000000   94.2636  265.8999   
2    1  44597U   12039H  19276.47170     0.000290   00000-0   38278-3   
3    2   44597  97.6163    285.60060  3284.000000   93.5867  266.5764   
4    1  44597U   12039H  19276.79277     0.000286   00000-0   37819-3   
..  ..     ...      ...          ...          ...       ...       ...   
815  2   44597  97.5847    178.48190  7592.000000  199.4179  160.6811   
816  1  44597U   12039H  20145.07463     0.006759   21838-3   11380-2   
817  2   44597  97.5863    179.61800  7928.000000  208.5078  151.5769   
818  1  44597U   12039H  20146.07319     0.007588   28686-3   11801-2   
819  2   44597  97.5867    180.75520  8326.000000  210.4701  149.6096   

             7      8  
0     0.000000   9991  
1    15.582627  32949  
2     0.000000   9994  
3    15.583229  33086  
4     0.000000   9992  
..         ...    ...  
815  16.014474  69589  
816   0.000000   9990  
817  16.027568  69749  
818   0.000000   9997  
819  16.041059  69901  

[820 rows x 9 columns]

In [14]:
line1 = []
line2 = []

for i in range(len(df)):
    if(i%2 == 0):
        line1.append("{}".format(df[0][i]))
    else:
        line2.append("{}".format(df[0][i]))

line1

['1 43680U 98067PR  18302.66341089  .00006443  00000-0  10000-3 0  9993',
 '1 43680U 98067PR  18303.17739464  .00037464  00000-0  54444-3 0  9995',
 '1 43680U 98067PR  18303.49864690  .00014167  00000-0  21094-3 0  9990',
 '1 43680U 98067PR  18304.20539707  .00006304  00000-0  97848-4 0  9993',
 '1 43680U 98067PR  18304.91214141  .00007066  00000-0  10878-3 0  9996',
 '1 43680U 98067PR  18305.49037694  .00010151  00000-0  15303-3 0  9993',
 '1 43680U 98067PR  18305.87586560  .00010789  00000-0  16214-3 0  9995',
 '1 43680U 98067PR  18306.51834116  .00011326  00000-0  16973-3 0  9990',
 '1 43680U 98067PR  18306.77532982  .00011422  00000-0  17107-3 0  9991',
 '1 43680U 98067PR  18307.54628884  .00011619  00000-0  17377-3 0  9991',
 '1 43680U 98067PR  18307.80327294  .00011762  00000-0  17578-3 0  9993',
 '1 43680U 98067PR  18308.83119953  .00011806  00000-0  17625-3 0  9990',
 '1 43680U 98067PR  18309.85910847  .00012153  00000-0  18103-3 0  9992',
 '1 43680U 98067PR  18309.92335216  .0

In [15]:
elevation = []
for x, y in zip(line1, line2):
    tle_rec = ephem.readtle(name, x, y)
    tle_rec.compute('{}'.format(tle_rec._epoch))
    elevation.append(tle_rec.elevation / 1000.0)
    
elevation

[399.3625,
 399.82721875,
 400.24775,
 400.3913125,
 400.09284375,
 399.87775,
 399.7524375,
 399.511125,
 399.41990625,
 399.31246875,
 399.2745625,
 399.1241875,
 398.950375,
 399.1374375,
 398.84284375,
 398.63646875,
 398.610125,
 398.31821875,
 398.31078125,
 398.2860625,
 398.3286875,
 398.39540625,
 398.40471875,
 398.44503125,
 398.497,
 398.60103125,
 398.5591875,
 398.559625,
 398.5440625,
 398.54465625,
 398.53965625,
 398.553625,
 398.60659375,
 398.62984375,
 398.73053125,
 398.80196875,
 398.8811875,
 398.926125,
 398.94709375,
 398.98625,
 398.9226875,
 398.96159375,
 398.96146875,
 398.821,
 398.85240625,
 399.00775,
 399.03890625,
 399.0423125,
 398.9328125,
 398.89453125,
 398.893125,
 398.760375,
 398.76853125,
 399.03203125,
 398.97825,
 399.23015625,
 399.24478125,
 399.403125,
 399.465125,
 399.74925,
 399.81309375,
 399.8174375,
 399.8935,
 399.8955,
 399.97971875,
 400.0575625,
 400.11421875,
 400.11471875,
 400.12203125,
 400.2658125,
 400.33671875,
 400.412906

In [16]:
elevation = np.array(elevation)

In [17]:
plt.figure(figsize = (20, 15))
plt.plot(elevation)

In [8]:
import datetime

def calc_epoch(epoch):
    # epoch year
    if (0 <= int(epoch[:2]) <= 20):
        year = int('20' + epoch[:2])
    else:
        year = int('19' + epoch[:2])
    
    epoch = epoch[2:].split('.')
    # day of year
    day_of_year = int(epoch[0]) - 1
    date = datetime.date(year, 1, 1) + datetime.timedelta(day_of_year)
    
    # extract month and day
    month = int(date.month)
    day = int(date.day)
    
    # decimal hour
    hour = int(float('0.' + epoch[1]) * 24.0)
    # decimal minute
    minute = int((float('0.' + epoch[1]) * 24.0 - hour) * 60.0)
    # decimal second
    sec = ((float('0.' + epoch[1]) * 24.0 - hour) * 60.0 - minute) * 60.0
    
    return year, month, day, hour, minute, sec

calc_epoch("97223.23211")

(1997, 8, 11, 5, 34, 14.303999999999917)

In [20]:
def tle2coes(tle_filename):
    with open(tle_filename, 'r') as f:
        lines = f.readlines()
    line1 = lines[0].strip().split()
    line2 = lines[1].strip().split()
    
    # epoch (year and day)
    epoch = line1[3]
    year, month, day = calc_epoch(epoch)
    
    # inclination
    i = float(line2[2])
    # right ascensison of the ascending node
    raan = float(line2[3])
    # eccentricity
    e_string = line2[4]
    e = float('0.' + e_string)
    # argument of perigee
    aop = float(line2[5])
    # mean anomaly
    M = float(line2[6])
    # mean motion
    n = float(line2[7][:11]) # revs/day
    
    return i, raan, e, aop, M, n, [year, month, day]

In [89]:
tle2coes('Tiangong.txt')

(42.7802,
 196.4777,
 0.0101297,
 130.5581,
 230.4736,
 16.03270706,
 [2011, 9.0, 29.0])

In [55]:
df = df[df.index % 2 != 0].drop(1, axis = 1)
df

2         3       4         5         6          7      8
1    97.6159  284.6393  3322.0   94.2636  265.8999  15.582627  32949
3    97.6163  285.6006  3284.0   93.5867  266.5764  15.583229  33086
5    97.6163  285.9439  3275.0   93.0785  267.0845  15.583395  33134
7    97.6164  286.6993  3252.0   92.7878  267.3749  15.583808  33243
9    97.6164  287.8669  3229.0   93.0812  267.0813  15.584476  33419
..       ...       ...     ...       ...       ...        ...    ...
811  97.5847  175.6484  6976.0  191.2273   168.885  15.986432  69182
813  97.5847  176.2145  7114.0  193.7236  166.3849  15.991339  69261
815  97.5847  178.4819  7592.0  199.4179  160.6811  16.014474  69589
817  97.5863  179.6180  7928.0  208.5078  151.5769  16.027568  69749
819  97.5867  180.7552  8326.0  210.4701  149.6096  16.041059  69901

[410 rows x 7 columns]

In [56]:
i = df.iloc[:, 0].values

In [57]:
for a in range(len(i)):
    i[a] = float(i[a])

i

array([97.6159, 97.6163, 97.6163, 97.6164, 97.6164, 97.6161, 97.6159,
       97.6163, 97.6162, 97.6159, 97.6157, 97.6157, 97.6156, 97.6154,
       97.6153, 97.6149, 97.6147, 97.6148, 97.6149, 97.6148, 97.615,
       97.6158, 97.6155, 97.6157, 97.6158, 97.6159, 97.6158, 97.616,
       97.6153, 97.6152, 97.615, 97.6149, 97.6146, 97.6144, 97.614,
       97.6143, 97.6141, 97.614, 97.6138, 97.6139, 97.6137, 97.6137,
       97.6139, 97.6143, 97.6146, 97.6146, 97.6147, 97.6146, 97.6146,
       97.6146, 97.6144, 97.6143, 97.6139, 97.6134, 97.6133, 97.613,
       97.613, 97.6129, 97.6127, 97.6126, 97.6127, 97.6126, 97.613,
       97.613, 97.6127, 97.6129, 97.6133, 97.6136, 97.6134, 97.6132,
       97.6132, 97.6129, 97.613, 97.6126, 97.6124, 97.6123, 97.6117,
       97.6116, 97.6118, 97.6113, 97.6109, 97.6112, 97.6112, 97.6115,
       97.612, 97.6122, 97.6119, 97.6118, 97.6119, 97.6119, 97.6117,
       97.6111, 97.6111, 97.6108, 97.6106, 97.6103, 97.6101, 97.6104,
       97.6103, 97.6101, 97.61,

In [58]:
plt.figure(figsize = (20, 15))
plt.plot(i)

In [59]:
raan = df.iloc[:, 1].values

for a in range(len(raan)):
    raan[a] = float(raan[a])

In [60]:
raan

array([284.6393, 285.6006, 285.9439, 286.6993, 287.8669, 289.3096,
       289.5154, 290.2721, 291.0964, 292.0582, 292.6081, 293.1577,
       293.6387, 294.5317, 295.2188, 296.3183, 297.4865, 298.517 ,
       300.0975, 300.5784, 301.4029, 302.0214, 303.259 , 303.8084,
       304.3585, 304.6333, 305.4583, 305.9395, 306.4892, 307.0392,
       307.5896, 308.1394, 308.621 , 309.2396, 309.9959, 310.2713,
       310.8209, 311.3713, 312.4713, 313.5715, 314.6031, 315.0843,
       315.7031, 316.6659, 317.7661, 317.8348, 318.867 , 319.899 ,
       321.3439, 322.0319, 322.5823, 323.1328, 324.7154, 325.4036,
       325.8852, 326.8485, 326.9861, 327.5364, 328.087 , 328.6374,
       329.5319, 329.6008, 330.6327, 331.1831, 332.2842, 332.7659,
       333.9364, 334.9689, 336.0015, 336.5523, 337.1028, 337.6535,
       338.1355, 339.2374, 340.2702, 340.4079, 341.3722, 341.716 ,
       342.7486, 343.8505, 344.9523, 345.9854, 346.1919, 346.7428,
       351.358 , 352.1158, 353.0115, 353.2872, 354.2518, 354.3

In [61]:
plt.figure(figsize = (20, 15))
plt.plot(raan)

In [62]:
aop = df.iloc[:, 3].values

for a in range(len(aop)):
    aop[a] = float(aop[a])

In [63]:
aop

array([94.2636, 93.5867, 93.0785, 92.7878, 93.0812, 91.3579, 91.5503,
       91.0847, 91.0377, 90.8332, 89.5941, 89.2446, 88.4334, 87.7981,
       87.6955, 87.1178, 86.5962, 86.4261, 84.1278, 86.4906, 83.8473,
       84.914, 83.6938, 85.0334, 84.0809, 83.9443, 83.8221, 83.8851,
       82.9504, 83.5278, 83.5543, 84.8185, 83.4145, 84.7625, 83.8138,
       84.1503, 82.9877, 84.1646, 84.3079, 83.9373, 85.0003, 84.8667,
       85.5079, 86.5922, 87.3457, 86.5372, 87.3682, 88.057, 88.3901,
       89.6122, 90.9775, 91.245, 92.1565, 92.316, 92.4632, 93.4999,
       93.7613, 95.364, 94.4887, 95.1577, 95.8582, 96.0019, 96.4727,
       96.4035, 94.9545, 95.7238, 99.3775, 100.1153, 101.0393, 99.2852,
       100.3394, 100.2422, 101.2622, 101.8453, 103.0085, 103.0, 104.4329,
       105.658, 106.1644, 106.3404, 105.9038, 105.5948, 105.2408, 106.135,
       104.738, 104.9944, 105.0594, 104.2556, 104.2652, 104.0181, 103.791,
       102.3162, 102.1499, 102.1036, 101.741, 101.615, 101.2551, 101.2429,
    

In [64]:
plt.figure(figsize = (20, 15))
plt.plot(aop)

In [65]:
M = df.iloc[:, 4].values

for a in range(len(M)):
    M[a] = float(M[a])

In [66]:
plt.figure(figsize = (20, 15))
plt.plot(M)

In [67]:
n = df.iloc[:, 5].values

for a in range(len(n)):
    n[a] = float(n[a])

In [68]:
plt.figure(figsize = (20, 15))
plt.plot(n)